config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :answers, only: [:new, :create, :show] do
      resources :scores, only: [:index, :new, :create, :show]
    end
    collection do
      get 'genre'
    end
  end
  resources :users, only: :show
end

app/models/question.rb
class Question < ApplicationRecord
# 記述の整理、視認性の確保の為にコメントアウトで情報を記載します
# アソシエーション関係
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  belongs_to :user
  has_many :answers
# アソシエーション関係
# バリデーションの設定
  FORBIDDEN_CHARACTERS_REGEX = /[死殺]/

  validates :genre_id, numericality: { other_than: 0, message: "は未選択では保存できません" }

  with_options presence: true do
    validates :user
    validates :question_name,
              format: { without: FORBIDDEN_CHARACTERS_REGEX, message: 'に、使ってはいけない文字が含まれています' }
    validates :question_content, uniqueness: { case_sensitive: true } ,
              format: { without: FORBIDDEN_CHARACTERS_REGEX, message: 'に、使ってはいけない文字が含まれています' }
    validates :model_answer,
              format: { without: FORBIDDEN_CHARACTERS_REGEX, message: 'に、使ってはいけない文字が含まれています' }
    validates :point,
              numericality: { only_integer: true, greater_than_or_equal_to: 10,
                              less_than_or_equal_to: 3000,
                              message: 'が設定できる範囲外です' }
  end
# バリデーションの設定
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :select_genre, only: [:index, :genre]
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :genre, :new, :create, :destroy ]

  def index
    @results = @p.result
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      render :new
    end
  end

  def genre
    @results = @p.result
    genre_id = params[:q][:genre_id_eq]
    @genre = Genre.find_by(id: genre_id)
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to root_path
    end
  end

  private

  def question_params
    params.require(:question).permit(:genre_id, :question_name, :question_content, :tip, :model_answer,
                                     :point).merge(user_id: current_user.id)
  end

  def select_genre
    @p = Question.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def move_to_index
    question = Question.find(params[:id])
    unless current_user.id == question.user_id
      redirect_to action: :index
    end
  end

  def set_question
    @question = Question.find(params[:id])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<%= render "shared/header" %>
<div class='new-question-main'>
  <h1>出題ページです</h1>
  <%= form_with model: @question,local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="question-form">
      ジャンルを選択してください<span class="indispensable">必須</span>
      <div class="question-jenre">
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>
      課題名を決めてください<span class="indispensable">必須</span>
      <div class="question-name">
        <%= f.text_field :question_name, class:"question-text", placeholder:"例) 簡単な足し算" %>
      </div>
      課題内容を入力してください<span class="indispensable">必須</span>
      <div class="question-content">
        <%= f.text_area :question_content, class:"question-text-area", placeholder:"例)10+5" %>
      </div>
      ヒントがあれば入力してください（任意)
      <div class="question-tip">
        <%= f.text_area :tip, class:"question-text-area", placeholder:"例)１の位と１０の位に注意してみよう" %>
      </div>
      模範解答を入力してください<span class="indispensable">必須</span>
      <div class="question-model-answer">
        <%= f.text_area :model_answer, class:"question-text-area", placeholder:"例)15" %>
      </div>
      獲得できる経験値量を入力してください<span class="indispensable">必須</span>
      <div class="question-point">
        <%= f.text_field :point, class:"question-text", placeholder:"例)300" %>
      </div>
      <div class="question-submit">
        <%= f.submit "変更する" ,class:"question-btn" %>
      </div>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>
</div>

app/views/questions/genre.html.erb
<%= render "shared/header" %>
<div class="genre-page">
  <% if @p.genre_id_eq.blank?%>
    <span class="search">すべてのもんだいです</span>
  <% else %>
    <span class="search"><%= "#{@genre.name}のもんだいページです" %></span>
  <% end %><br>

  <%# 検索結果の個数で条件分岐 %>
  <div class="genre-list">
    <% if @results.length !=0 %>
      <% @results.each do |result| %>
        
        <div class="question-title" >
          <li class="genre-li">
          <% if @p.genre_id_eq.blank? %>
            <span class="genre---li"><%= "《#{result.genre.name}》" %></span>
          <% end %>
          <%= link_to result.question_name, new_question_answer_path(question_id: result.id ) ,class: "genre-question-name", id: "button" %>
          <%# 出題者のみ編集・削除機能を表示する条件分岐 %>
          <% if user_signed_in? %>
            <% if current_user.id == result.user_id %>
              <span class="show-lists hidden" , id="lists">◇
                <%= link_to "編集", edit_question_path(result.id), method: :get,    class:"question-link" %>
                <% if result.answers.blank? %>
                  <%= link_to "削除", question_path(result.id),    method: :delete, class:"question-link" %>
                <% else %>
                  <span class="question-link">※すでに解答者がいる為、削除はできません</span>
                <% end %>
              </span>
            <% end %>
          <% end %>
          <%# 出題者のみ編集・削除機能を表示する条件分岐 %>

          <%# 解答履歴の有無でチェック表示を条件分岐 %>
          <% if result.answers.present? %>
            <% result.answers.each do |answer| %>
              <% if user_signed_in? && answer.user.id == current_user.id %>
                <span class="check">✅</span>
              <% end %>
            <% end %>
          <% end %>
          <%# 解答履歴の有無でチェック表示を条件分岐 %>

          <br>
          <span class="genre-tip">(ヒント：<%= result.tip %>）</span>
          <span class="genre-user"> ✨ 出題者：<%= result.user.nickname %></span>
          </li>
        </div>
      <% end %>
    <% else %>
      <span class="search-result-none">ざんねん...もんだいは、まだありません</span>
    <% end %>
  </div>
  <%# 検索結果の個数で条件分岐 %>

  <div class="root-path-link">
    <%= link_to 'トップページへ戻る', root_path ,class: "root-path-link"%>
  </div>
</div>

app/views/questions/index.html.erb
<%= render "shared/header" %>
<div class = main>
  <%# 画面上部の「人生を変える学習アプリ」の帯部分 %>
    <div class='title-contents'>
      <h2 class='service-title'>
        人生を変える学習アプリ
      </h2>
      <p class='service-explain'>
        SPP_APPはだれでもお勉強が好きになれる。自分でもできる自信がつく。
      </p>
      <p class='service-explain'>
        そんな学習アプリです。
      </p>
      <p class='service-explain'>
        さぁ、やればできる！学ぶ楽しさを体験しよう！
      </p>
    </div>
  <%# 画面上部の「人生を変える学習アプリ」の帯部分 %>

  <%# 課題を選ぶ %>
  <div class="genre-select-field" >
    <%= search_form_for @p, url: genre_questions_path do |f| %>
      <%= f.label :genre_id_eq, 'なんのかもくにチャレンジしますか？',class:"genre-select-label" %>
      <div class="genre-select-pulldown" >
        <%= f.collection_select :genre_id_eq, Genre.where.not(id: 0), :id, :name, include_blank: '---' %>
        <span class="finger">👈</span>
      </div>
      <%= f.submit 'もんだいをえらぶ' %>
    <% end %>
  </div>
  <%# 課題を選ぶ %>
  <%#  ネオン文字部分 %>
  <div class="neon">
    <div class="YDK1">tu peux le faire si tu essaies</div>
    <div class="YDK2">you can do it if you try</div>
    <div class="YDK3">やればできる</div>
    <div class="YDK4">Si Potes Probare</div>
    <div class="YDK5">ティモンディ高岸宏行さん</div>
  </div>
  <%#  ネオン文字部分 %>
  <%# 課題作成ボタン %>
  <%= link_to(new_question_path, class: 'new-question-btn') do %>
    <span class='new-question-btn-text'>課題を作成する</span>
    <%= image_tag 'sozai_cman_jp_20210625151446.png' , size: '185x50' ,class: "new-question-btn-icon" %>
  <% end %>
  <%# 課題作成ボタン %>

  <div class="questions">
    <div class="math">
      <div class="subjects">
        <span class="subject">さんすう</span>
      </div>
      <% @questions.each do |question| %>
        <li class='list'>
          <% if question.genre_id == 2 %>
            <span class="question-num"><%= "《No.#{question.id}》" %></span>
            <%= link_to question.question_name, new_question_answer_path(question.id) ,class: "top-page-question-name", id: "button" %>
          <% end %>
        </li>
      <% end %>
    </div>
    <div class="japanese">
      <div class="subjects">
        <span class="subject">こくご</span>
      </div>
      <% @questions.each do |question| %>
        <li class='list'>
          <% if question.genre_id == 1 %>
            <span class="question-num"><%= "《No.#{question.id}》" %></span>
            <%= link_to question.question_name, new_question_answer_path(question.id) ,class: "top-page-question-name", id: "button" %>
          <% end %>
        </li>
      <% end %>
    </div>
    <div class="english">
      <div class="subjects">
        <span class="subject">えいご</span>
      </div>
      <% @questions.each do |question| %>
        <li class='list'>
          <% if question.genre_id == 3 %>
            <span class="question-num"><%= "《No.#{question.id}》" %></span>
            <%= link_to question.question_name, new_question_answer_path(question.id) ,class: "top-page-question-name", id: "button" %>
          <% end %>
        </li>
      <% end %>
    </div>
  </div>


</div>

app/views/questions/new.html.erb
<%= render "shared/header" %>
<div class='new-question-main'>
  <h1>出題ページです</h1><br/>
  <%= form_with model: @question,local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %><br/>
    <div class="question-form">
      ジャンルを選択してください<span class="indispensable">必須</span>
      <div class="question-jenre">
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>
      課題名を決めてください<span class="indispensable">必須</span>
      <div class="question-name">
        <%= f.text_field :question_name, class:"question-text", placeholder:"例) 簡単な足し算" %>
      </div>
      課題内容を入力してください<span class="indispensable">必須</span>
      <div class="question-content">
        <%= f.text_area :question_content, class:"question-text-area", placeholder:"例)10+5" %>
      </div>
      ヒントがあれば入力してください（任意)
      <div class="question-tip">
        <%= f.text_area :tip, class:"question-text-area", placeholder:"例)１の位と１０の位に注意してみよう" %>
      </div>
      模範解答を入力してください<span class="indispensable">必須</span>
      <div class="question-model-answer">
        <%= f.text_area :model_answer, class:"question-text-area", placeholder:"例)15" %>
      </div>
      獲得できる経験値量を入力してください<span class="indispensable">必須</span>
      <div class="question-point">
        <%= f.text_field :point, class:"question-point", placeholder:"例)300" %>
      </div>
      <div class="question-submit">
        <%= f.submit "出題する" ,class:"question-btn" %>
      </div>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>
</div>