config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :answers, only: [:new, :create, :show] do
      resources :scores, only: [:index, :new, :create, :show]
    end
    collection do
      get 'genre'
    end
  end
  resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  has_many :scores

  with_options presence: true do
    validates :nickname
    validates :character, presence: {message: 'をえらんでください' }
    validates :character_name
    validates :level
    validates :experience_point
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @answers = @user.answers.includes(:user)
    @levelSetting = LevelSetting.find_by(level: current_user.level + 1)
    
    gon.thresold = @levelSetting.thresold
    gon.experience_point = @user.experience_point
  end

  def move_to_index
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      redirect_to root_path 
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_answer.html.erb
<div class="my-page-score">
  <span class="answer-question-id">
    <%= "【#{answer.question.genre.name}】"%>
    <%= " 《 No.#{answer.question.id} 》"%>
  </span>
  <span>
    <% if answer.score.present?%>
      <%= link_to answer.question.question_name, question_answer_score_path(answer.question.id,answer.id,answer.score.id), class:"user-answer-link" %>
    <% else %>
      <%= link_to answer.question.question_name, question_answer_path(answer.question.id,answer.id), method: :GET , class:"user-answer-link" %>
    <% end %>
  </span>
  <span class="user-answer-score">
    <% if answer.score.present?%>
      <%= "#{answer.score.score}てん"%>
    <% else %>
      <%= link_to 'こたえあわせをする', new_question_answer_score_path(answer.question.id,answer.id) ,class: "check-the-answer-later" %>
    <% end %>
  </span>
</div>

app/views/users/_character_image.html.erb
<%# キャラクターの画像 %>
<div class="character">
  <div class="character-image">
    <% if @user.character == "カブトムシ" %>
      <% if @user.character_name == "たまご" %>
        <%= image_tag 'KmoyUFSKciHfvBm1625672324.jpg',class: "character-image" %>
      <% elsif @user.character_name == "ようちゅう" %>
        <%= image_tag 'Bs2Hf8NnbGYtOC41625661275.jpg',class: "character-image" %>
      <% elsif @user.character_name == "サナギ" %>
        <%= image_tag 'giSTRQ8qlKQwedf1625662424.jpg',class: "character-image" %>
      <% elsif @user.character_name == "カブトムシ" %>
        <%= image_tag 'R0iOvGM4huUvR0S1625663994.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のカブトムシの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kabutomusi/',class:"quote-link" %>
      <% elsif @user.character_name == "エレファスゾウカブト" %>
        <%= image_tag 'kqv46k5CrXuBPNC1625665270.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のカブトムシの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kabutomusi/',class:"quote-link" %>
      <% elsif @user.character_name == "アトラスオオカブト" %>
        <%= image_tag '93oxFmLSBueOjxB1625666620.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のカブトムシの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kabutomusi/',class:"quote-link" %>
      <% elsif @user.character_name == "ネプチューンオオカブト" %>
        <%= image_tag 'Ny76l1lu9RX2RZW1625668333.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のカブトムシの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kabutomusi/',class:"quote-link" %>
      <% elsif @user.character_name == "コーカサスオオカブト" %>
        <%= image_tag 'RcUNZ5LBZYhKWaR1625669449.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のカブトムシの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kabutomusi/',class:"quote-link" %>
      <% elsif @user.character_name == "ヘラクレスオオカブト" %>
        <%= image_tag 's4ai7ssW6K6DQnt1625671135.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のカブトムシの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kabutomusi/',class:"quote-link" %>
      <% else %>
      <% end %>
    <% end %>
    <% if @user.character == "クワガタムシ" %>
      <% if @user.character_name == "たまご" %>
        <%= image_tag 'KmoyUFSKciHfvBm1625672324.jpg',class: "character-image" %>
      <% elsif @user.character_name == "ようちゅう" %>
        <%= image_tag 'Bs2Hf8NnbGYtOC41625661275.jpg',class: "character-image" %>
      <% elsif @user.character_name == "サナギ" %>
        <%= image_tag 'wIwxIugqbYbwHyj1626751547.jpg',class: "character-image" %>
      <% elsif @user.character_name == "クワガタムシ" %>
        <%= image_tag 'kSyknmhD5BURdcY1626741402.jpg',class: "character-image" %>
      <% elsif @user.character_name == "グランディスオオクワガタ" %>
        <%= image_tag 'sV8rsCXmUXZTr8V1626742736.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のクワガタの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kuwagata/',class:"quote-link" %>
      <% elsif @user.character_name == "ギラファノコギリクワガタ" %>
        <%= image_tag 'u7PYUYoKek4Ru6N1626743929.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のクワガタの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kuwagata/',class:"quote-link" %>
      <% elsif @user.character_name == "ジュダイクスミヤマクワガタ" %>
        <%= image_tag 'u9V6YGU7TRz8X791626745035.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のクワガタの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kuwagata/',class:"quote-link" %>
      <% elsif @user.character_name == "パラワンオオヒラタクワガタ" %>
        <%= image_tag 'P6NYjwph4KQS8vo1626750072.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のクワガタの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kuwagata/',class:"quote-link" %>
      <% elsif @user.character_name == "スマトラオオヒラタクワガタ" %>
        <%= image_tag 'G3KDUBCMhbYhe3Y1626750867.jpg',class: "character-image" %>
        <%= link_to '参考資料 : 最強のクワガタの種類一覧と強さランキングTOP10', 'https://dangerous-creatures.com/kuwagata/',class:"quote-link" %>
      <% else %>
      <% end %>
    <% end %>
  </div>
</div>
<%# キャラクターの画像 %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="my-page">
  <div class="inner">
    <%# マイページヘッダー２部分 %>
    <h2 class="page-heading">
      <%= "#{@user.nickname}さんのマイページ" %>
    </h2>
    <%# マイページヘッダー２部分 %>
    <div class="user__wrapper">
      <%# プロフィール部分 %>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">なまえ</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">レベル</th>
            <td class="table__col2"><%= @user.level %></td>
          </tr>
          <tr>
            <th class="table__col1">キャラクター</th>
            <td class="table__col2"><%= @user.character_name %></td>
          </tr>
        </tbody>
      </table>
      <%# プロフィール部分 %>
      <%# 経験値グラフ部分 %>
      <div class="point-parameter">
        <div class="users-point">
          <div>
            <%= "レベル#{@user.level+1}まで" %>
          </div>
          <div class="necessary-point" id="necessary-point">
            <%= "#{@levelSetting.thresold}ポイントひつよう" %>
          </div>
          <canvas class="myChart" id="myChart"  width="600" height="140"></canvas>
          <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
          <div>
            <%= "げんざい#{@user.experience_point}ポイント" %>
          </div>
          <div>
            <%= "あと#{@levelSetting.thresold - @user.experience_point}ポイント！！" %>
          </div>
        </div>
      </div>
    </div>
    <%# 経験値グラフ部分 %>
    <%# キャラクターの画像 %>
      <%= render partial: '/users/character_image' %>
    <%# キャラクターの画像 %>
      <%# 解答履歴を表示 %>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの こたえてきたもんだいたち" %>
      </h2>
      <div class="user__card">
        <%= render partial: '/users/answer', collection: @answers %>
      </div>
      <%# 解答履歴を表示 %>
  </div>
</div>